import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Tenant business code (domain-implementation-plan.md §0.5.2) reaches data ONLY through `auth.tenant.run` /
  // `forTenant`: it may not import the raw Prisma client (an unscoped query), and it may not mint a
  // `VerifiedTenantId` itself (`trustedTenantId` is for resolve-tenant.ts, the setup route and audit.ts).
  {
    files: ["src/app/(app)/schools/**/*.{ts,tsx}", "src/app/api/v1/schools/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            { name: "@/lib/db", message: "School code must use the tenant context (auth.tenant.run / forTenant), never the raw client." },
            { name: "@/lib/tenant/verified-tenant", message: "Only resolve-tenant.ts, the setup route and audit.ts may mint a VerifiedTenantId." },
          ],
        },
      ],
      // `User` has no tenant column, so row-level security cannot protect it: a query on it from school code could return anyone on
      // the platform. People are read THROUGH `tenantMembership` (lib/members/service.ts) with a narrow `select` on the relation.
      "no-restricted-syntax": [
        "error",
        {
          selector: "MemberExpression[property.name='user'][object.name=/^(tx|prisma|db|client)$/]",
          message: "School code must not query `user` directly (no tenant column, so RLS can't protect it): read people through `tenantMembership` — see lib/members/service.ts.",
        },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the test runner (tests/README.md) — not source.
    "playwright-report/**",
    "test-results/**",
    "tests/.tmp/**",
  ]),
]);

export default eslintConfig;
